version: "3.8"
services:
  php8.1:
    container_name: php_8.1
    build:
      context: ./docker/php/8.1
    volumes:
      - .:/var/www/html
  php8.2:
    container_name: php_8.2
    build:
      context: ./docker/php/8.2
    volumes:
      - .:/var/www/html
  server-18:
    build:
      context: docker/node/18
    volumes:
      - .:/usr/src/app
  server-20:
    build:
      context: docker/node/20
    volumes:
      - .:/usr/src/app
  server-22:
    build:
      context: docker/node/22
    volumes:
      - .:/usr/src/app
