version: '3.8'
services:
  php8.1:
    container_name: php_8.1
    build:
      context: ./docker/php/8.1
    volumes:
      - .:/var/www/html
  php8.2:
    container_name: php_8.2
    build:
      context: ./docker/php/8.2
    volumes:
      - .:/var/www/html

